import type { Metadata } from "next";
import { Cormorant_Garamond, Poppins } from "next/font/google";
import "./globals.css";

// Download fonts via Next.js
const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300","400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Eldeco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* Inject CSS variables globally */}
      <body className={`${cormorant.variable} ${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
